name: tatar_shower
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.3.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/light-images/background.png
    - assets/light-images/liquid.png
    - assets/light-images/shower.png
    - assets/light-images/clock.png
    - assets/light-images/calendar.png
    - assets/light-images/run.png
    - assets/light-images/target.png
    - assets/light-images/frozen.png
    - assets/light-images/bottomIcons/bottomCalendar.png
    - assets/light-images/bottomIcons/bottomClock.png
    - assets/light-images/bottomIcons/bottomSettings.png
  fonts:
    - family: RussoOne
      fonts:
        - asset: assets/fonts/russoOne.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
  generate: true  

